#pragma once

#include "NightlyVer.h"
#include "BuildVer.h"
#define TOSTRING2(arg) #arg
#define TOSTRING(arg) TOSTRING2(arg)
#ifdef BML_NIGHTLY_VER
#define BML_VERSION TOSTRING(BML_MAJOR_VER) "." TOSTRING(BML_MINOR_VER) "." TOSTRING(BML_BUILD_VER) "." BML_NIGHTLY_VER
#define BML_RC_VERSION TOSTRING(BML_MAJOR_VER) "." TOSTRING(BML_MINOR_VER) "." TOSTRING(BML_BUILD_VER) "." BML_NIGHTLY_VER
#else
#define BML_VERSION TOSTRING(BML_MAJOR_VER) "." TOSTRING(BML_MINOR_VER) "." TOSTRING(BML_BUILD_VER)
#define BML_RC_VERSION TOSTRING(BML_MAJOR_VER) "." TOSTRING(BML_MINOR_VER) "." TOSTRING(BML_BUILD_VER) ".0"
#endif


