name: BallanceModLoader Nightly Build

on:
  push:
    branches:
      - "patch-nightly"

jobs:
  msvc-build:
  
    strategy:
      matrix:
        vs: ['2019']
        msvc_arch: ['x86']

    runs-on: windows-2019

    steps:
    - name: Fetching Repository
      uses: actions/checkout@v3
      with:
        ref: "patch-nightly"
    - name: Getting Commit Hash
      id: get_hash
      uses: pr-mpt/actions-commit-hash@v1
    - name: Generating Variables
      shell: cmd
      run: |
        echo version = [0, 3, 40] >> bml_config.py
        echo nightly = "${{ steps.get_hash.outputs.short }}" >> bml_config.py
        echo deploy_path = "Build" >> bml_config.py
        echo bmlmods_path = "" >> bml_config.py
    - name: Building BallanceModLoader
      shell: cmd
      run: |
        set VS=${{ matrix.vs }}
        set VCVARS="C:\Program Files (x86)\Microsoft Visual Studio\%VS%\Enterprise\VC\Auxiliary\Build\vcvarsall.bat"
        if not exist %VCVARS% set VCVARS="C:\Program Files\Microsoft Visual Studio\%VS%\Enterprise\VC\Auxiliary\Build\vcvarsall.bat"
        call %VCVARS% ${{ matrix.msvc_arch }}
        MSBuild BML.sln -p:Platform=x86
    - name: Uploading Nightly Build
      uses: actions/upload-artifact@v3
      with:
        name: bmlmods-nightly
        path: Dist/Dev/BML-*-dev.zip
        retention-days: 30
